spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 620351269398-daqfinfd134srlcps4pqkhetf1v4lgaj.apps.googleusercontent.com
            client-secret: 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
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration