spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 76537276579-bcjenqo2bf158pd7h1fls5kohv718f55.apps.googleusercontent.com
            client-secret: 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